name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # refresh twice a day
  workflow_dispatch: {}

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Avnish-kaushik
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push snake output to the output branch of the profile repo
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          repo: Avnish-kaushik/Avnish-kaushik
        env:
          GH_PAT: ${{ secrets.PROFILE_TOKEN }}
